### ISSUE TITLE
ValSingleTest.java:33: <body>Improve test coverage and...

### ISSUE THREAD

**Issue by 0pdd** [pragmatic-objects/oo-atom#109]
The puzzle `8-cec8a65b` from #8 has to be resolved:

https://github.com/project-avral/oo-atom/blob/5ed6fdc1387a540a335b798f80b3f5586b9e203d/atom-basis/src/test/java/oo/atom/codegen/bytebuddy/validator/ValSingleTest.java#L33-L33

The puzzle was created by Kapralov Sergey on 04-Nov-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@skapral please pay attention to this new issue.

**Comment by skapral** [comment]
Deprecated by #184
