### ISSUE TITLE
AtomizerMain.java:93: <body>In aggro mode,...

### ISSUE THREAD

**Issue by 0pdd** [pragmatic-objects/oo-atom#111]
The puzzle `99-a8b3c755` from #99 has to be resolved:

https://github.com/project-avral/oo-atom/blob/5ed6fdc1387a540a335b798f80b3f5586b9e203d/atom-basis/src/main/java/oo/atom/codegen/AtomizerMain.java#L93-L93

The puzzle was created by Kapralov Sergey on 29-Nov-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@skapral please pay attention to this new issue.

**Comment by skapral** [comment]
Duplicate for #181
